import {
  LucidePhone,
  LucideMail,
  LucideMapPin,
  LucideClock,
  LucideMessageCircle,
  LucideUsers,
  LucideShare2,
  LucideCamera,
  LucideTarget,
  LucideCrown,
  LucideEye,
  LucideTimer,
  LucideStar,
  LucideGauge,
  LucideHotel,
  LucideUtensils,
  LucideCheck,
  LucideX,
  LucidePlus,
  LucideMinus,
  LucideChevronDown,
  LucideChevronUp,
  LucideZoomIn,
  LucideHouse,
  LucideMountain,
  LucideSearch,
  LucideInbox,
  LucideCalendar,
  LucideArrowRight,
  LucideArrowLeft,
  LucideCircleCheck,
} from '@lucide/angular';

/** Lucide icons used across the site — import/export via SharedModule. */
export const LUCIDE_ICONS = [
  LucidePhone,
  LucideMail,
  LucideMapPin,
  LucideClock,
  LucideMessageCircle,
  LucideUsers,
  LucideShare2,
  LucideCamera,
  LucideTarget,
  LucideCrown,
  LucideEye,
  LucideTimer,
  LucideStar,
  LucideGauge,
  LucideHotel,
  LucideUtensils,
  LucideCheck,
  LucideX,
  LucidePlus,
  LucideMinus,
  LucideChevronDown,
  LucideChevronUp,
  LucideZoomIn,
  LucideHouse,
  LucideMountain,
  LucideSearch,
  LucideInbox,
  LucideCalendar,
  LucideArrowRight,
  LucideArrowLeft,
  LucideCircleCheck,
] as const;
